#! /bin/bash
# Name : autocomp
# Func : 
# Time : 2015-10-13 13:18:33


function _autocomp()
{
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    local opts="-h --help -f --file"

    if [[ ${cur} == -* ]] ; then
        COMPREPLY=($(compgen -W "${opts}" --${cur}))
        return 0
    fi
}

complete -F _autocomp autocomp
