#! /bin/bash
# Name : bpc
# Func : 
# Time : 2015-07-08 19:32:25

# check CONF_PATH whether exist
if test -z "$CONF_PATH" ; then
    exit 1
fi

# update local config to system
if test "$1" = "-u" -o "$1" = "u" ; then
    test ! -d $CONF_PATH && exit 1
    # update vim , tmux amd emacs config
    cp -uvp $CONF_PATH/vim-conf/.vimrc ~/.vimrc 
    # cp -uvpr $CONF_PATH/vim-conf/.vim ~
    # cp -uvp $CONF_PATH/emacs-conf/.emacs ~/.emacs 
    cp -uvp $CONF_PATH/tmux-conf/.tmux.conf ~/.tmux.conf 

    # update bash config
    cp -uvp $CONF_PATH/bash-conf/.profile ~/.profile 
    cp -uvp $CONF_PATH/bash-conf/.bashrc ~/.bashrc 
    cp -uvp $CONF_PATH/bash-conf/.home_info ~/.home_info 

    # update shared library config and others
    cp -uvp $CONF_PATH/other/protocols /etc/protocols 
    cp -uvp $CONF_PATH/other/ld.so.conf /etc/ld.so.conf 

fi

# backup config
if test -d $CONF_PATH; then
    # backup vim and tmux config
    cp -uvp ~/.vimrc $CONF_PATH/vim-conf 
    cp -uvp ~/.tmux.conf $CONF_PATH/tmux-conf 
    #cp -uvpr ~/.vim $CONF_PATH/vim-conf 
    #tar -cvf usr-share-vim.tar /usr/share/vim/addons/ /usr/share/vim/vim72
    #tar -cvf etc-vim.tar /etc/vim

    # backup emacs config
    #cp -uvpr ~/_emacs $CONF_PATH
    #cp -uvpr ~/.emacs.d $CONF_PATH
    #cp -uvp ~/.emacs $CONF_PATH/emacs-conf

    # backup bash config
    cp -uvp ~/.profile $CONF_PATH/bash-conf 
    cp -uvp ~/.bashrc $CONF_PATH/bash-conf 
    cp -uvp ~/.home_info $CONF_PATH/bash-conf 
    
    # backup shared library config and others
    cp -uvp /etc/protocols $CONF_PATH/other 
    cp -uvp /etc/ld.so.conf $CONF_PATH/other 
else
    echo "path not exist"
fi
