#! /bin/bash
# Name : certs_gen
# Func : generate ipsec certificate
# Time : 2015-12-03 13:09:37

# \brief printf usage of shell script
# \param $@ [in] paramters from cmd line
# \return 0, if succ
#        -1, if fail
function print_usage()
{
    echo -e "\e[1;31m#-------------------Shell Usage------------------#"
    echo "Usage  : $(basename $0) [options] script-name"
    echo "Options: "
    echo "     -h,--help    Show usage of shell"
    echo "     --ca         Include CA basicConstraint, default: no"
    echo "     --cadn       Generate CA certificate with this subject dn"
    echo "     --cakey      Generate certificate with this CA private key"
    echo "     --cacert     Generate certificate with this CA certificate"
    echo "     --dn         Generate certificate with subject dn"
    echo "     --name       Certificate name"
    echo "     --outform    Encoding of generated cert, default: der"
    echo "     --lifetime   Certificate lifetime"
    echo "     --digest     Generate certificate digest for signature creation"
    echo "     --req        Generate certificate request"
    echo "     --private    Generate private key"
    echo "     --pub        Generate public key"
    echo "     --package    Package certificates, key and ipsec configuations"
    echo "     --cert       Certificate"
    echo "     --key        Private key of certificate"
    echo -e "#-------------------Shell Usage-------------------#\e[0m"
}

# \brief get paramters from cmd line
# \param $@ [in] paramters from cmd line
# \return 0, if succ
#        -1, if fail
function parser_args()
{
    for ((i = 1; i <= $#; i++)); do
        case "${!i}" in
            -h|--help) print_usage $@; shift ;;
            --ca) ca=1 ;;
            --cadn)
                ((start=i+1))
                for ((ii = $start; ii <= $#; ii++)); do
                    opt=${!ii}
                    test "${opt:0:1}" = "-" && i=$ii && break 
                    ca_dn+=$opt

                    ((j=ii+1))
                    opt=${!j}
                    test -z "$opt" -o "${opt:0:1}" = "-" && i=$ii && break 
                    ca_dn+=" "
                done
                test -z "$ca_dn" && echo "Option ${!i} need a paramter!" && exit 1
                ca_dn=${ca_dn//|/ }
                ;;
            --caname)
                ((i=i+1))
                ca_name=${!i} ; 
                test -z "$ca_name" && echo "Option ${!i} need a paramter!" && exit 1
                ;;
            --cakey) 
                ((i=i+1))
                ca_private_key=${!i}
                test -z "$ca_private_key" && echo "Option ${!i} need a paramter!" && exit 1
                ;;
            --cacert) 
                ((i=i+1))
                ca_cert=${!i}; 
                test -z "$ca_cert" && echo "Option ${!i} need a paramter!" && exit 1
                ;;
            --dn)
                ((start=i+1))
                for ((ii = $start; ii <= $#; ii++)); do
                    opt=${!ii}
                    test "${opt:0:1}" = "-" && i=$ii && break 
                    dn+=$opt

                    ((j=ii+1))
                    opt=${!j}
                    test -z "$opt" -o "${opt:0:1}" = "-" && i=$ii && break 
                    dn+=" "
                done
                test -z "$dn" && echo "Option ${!i} need a paramter!" && exit 1
                dn=${dn//|/ }
                ;;
            -o|--outform) 
                ((i=i+1))
                outform=${!i}; 
                test -z "$outform" && echo "Option ${!i} need a paramter!" && exit 1
                ;;
            -l|--lifetime) 
                ((i=i+1))
                lifetime=${!i}; 
                test -z "$lifetime" && echo "Option ${!i} need a paramter!" && exit 1
                ;;
            -n|--name) 
                ((i=i+1))
                name=${!i}; 
                test -z "$name" && echo "Option ${!i} need a paramter!" && exit 1
                ;;
            -f|--file) 
                ((i=i+1))
                file=${!i}; 
                test -z "$ca_cert" && echo "Option ${!i} need a paramter!" && exit 1
                ;;
            --delete)
                delete_flag=1 
                ((start=i+1))
                for ((ii = $start; ii <= $#; ii++)); do
                    opt=${!ii}
                    test "${opt:0:1}" = "-" && i=$ii && break 
                    dn+=$opt

                    ((j=ii+1))
                    opt=${!j}
                    test -z "$opt" -o "${opt:0:1}" = "-" && i=$ii && break 
                    dn+=" "
                done
                test -z "$dn" && echo "Option ${!i} need a paramter!" && exit 1
                dn=${dn//|/ }
                ;;
            --private)
                gen_private_key=1 
                ((i=i+1))
                private_key=${!i}; 
                test -z "$private_key" && echo "Option ${!i} need a paramter!" && exit 1
                ;;
            --pub)
                gen_public_key=1 
                ((i=i+1))
                public_key=${!i}; 
                test -z "$public_key" && echo "Option ${!i} need a paramter!" && exit 1
                ;;
            --type)
                ((i=i+1))
                type=${!i}; 
                test -z "$$type" && echo "Option ${!i} need a paramter!" && exit 1
                ;;
            --req)
                gen_req=1 
                ((start=i+1))
                for ((ii = $start; ii <= $#; ii++)); do
                    opt=${!ii}
                    test "${opt:0:1}" = "-" && i=$ii && break 
                    dn+=$opt

                    ((j=ii+1))
                    opt=${!j}
                    test -z "$opt" -o "${opt:0:1}" = "-" && i=$ii && break 
                    dn+=" "
                done
                test -z "$dn" && echo "Option ${!i} need a paramter!" && exit 1
                dn=${dn//|/ }
                ;;
            --package)
                package_certs=1
                ((i=i+1))
                name=${!i}; 
                test -z "$name" && echo "Option ${!i} need a paramter!" && exit 1
                ;;
            --cert)
                ((i=i+1))
                certs_cert=${!i}; 
                test -z "$certs_cert" && echo "Option ${!i} need a paramter!" && exit 1
                ;;
            --key)
                ((i=i+1))
                certs_private_key=${!i}; 
                test -z "$certs_private_key" && echo "Option ${!i} need a paramter!" && exit 1
                ;;
            --client)
                client_flag=1 ;;
            --server)
                server_flag=1 ;;
            --custom)
                custom_flag=1 ;;
            --) break ;;
            *) echo "${!i} Internal error!" ; exit 1 ;;
        esac
    done

    return 0
}

get_value (){
    test $# -lt 1 && echo "" && return 0
    sed -n "s/$1[=:]//p" $file
}

get_para_from_conf (){
    ca_name=`get_value caname`
    ca_dn=`get_value cadn`
    test -n "$ca_dn" && ca_dn=${ca_dn//\"/}
    ca_cert=`get_value cacert`
    ca_private_key=`get_value cakey`
    lifetime=`get_value lifetime`
    outform=`get_value outform`
    cert_dn=`get_value certdn`
    test -n "$cert_dn" && cert_dn=${cert_dn//\"/}
    cert_name=`get_value certname`
    digest=`get_value digest`
}

get_subject_from_cert() {
    test ! -e $1 && echo ""
    ipsec pki --print --in $certs_cert | grep "subject" | sed "s/.*:\ *\"*\(.*\)\"$/\1/g"
}

get_issuer_from_cert() {
    test ! -e $1 && echo ""
    ipsec pki --print --in $certs_cert | grep "issuer" | sed "s/.*:\ *\"*\(.*\)\"$/\1/g"
}

certs_package (){
    if test ! -e $package_path ; then
        mkdir $package_path && mkdir $package_path/ipsec.d 
        cd $package_path/ipsec.d
        mkdir aacerts acerts cacerts certs crls ocspcerts private reqs
    fi

    rm -f $package_path/ipsec.d/cacerts/*
    rm -f $package_path/ipsec.d/certs/*
    rm -f $package_path/ipsec.d/private/*
    rm -f $package_path/ipsec.secrets
    rm -f $package_path/ipsec.conf
    cp $ca_cert $package_path/ipsec.d/cacerts/
    cp $certs_cert $package_path/ipsec.d/certs/
    cp $certs_private_key $package_path/ipsec.d/private/

    ##
    # copy ispec conf and secrets
    ##
    if test $custom_flag -eq 1 ; then
        echo > $package_path/ipsec.secrets
    else
        cp $IPSEC_PATH/conf/ipsec.secrets $package_path/
    fi
    if test $custom_flag -eq 1 ; then
        cp $IPSEC_PATH/conf/ipsec.conf.custom $package_path/ipsec.conf
    else
        if test $server_flag -eq 1 ; then
            cp $IPSEC_PATH/conf/ipsec.conf.server $package_path/ipsec.conf
        else
            cp $IPSEC_PATH/conf/ipsec.conf.client $package_path/ipsec.conf
        fi
    fi

    tar_path=`pwd`
    cd $package_path/

    ipaddr=`ifconfig | grep "inet\ .*:.*:.*:.*" | sed "s/.*inet.*:\(.*\)\ .*:.*:.*$/\1/g"`
    sed -i "s/right=.*/right=$ipaddr/g" ipsec.conf
    has_private_secret=`grep "$dn" ipsec.secrets`
    if test -z "$has_private_secret" ; then
        echo "\"$dn\" : RSA `basename $certs_private_key`" >> ipsec.secrets
    else
        sed -i "/$dn/s/.*/\"$dn\" : RSA `basename $certs_private_key`" ipsec.secrets
    fi
    sed -i "/leftid/s/\(.*\)leftid.*/\1leftid=\"$dn\"/g" ipsec.conf
    sed -i "/leftcert/s/\(.*\)leftcert.*/\1leftcert=`basename $certs_cert`/g" ipsec.conf

    tar -cf $tar_path/${name}.tar ipsec.conf ipsec.secrets ipsec.d
    test $? -eq 0 && echo "Package Certificate \"$dn\" successfully!" && exit 0
    
}

ca_certs_delete() {
    if test "$dn" = "all" ; then
        rm -f $ipsec_ca_save_file
        rm -f $ipsec_certs_save_file
        rm -rf $certs_gen_path/ca/*
        rm -rf $certs_gen_path/certs/*

        echo "Delete all ipsec certificates, keys and configuations!" && exit 0
    fi

    test ! -e $ipsec_ca_save_file -a ! -e $ipsec_certs_save_file && exit 1
    delete_result=`grep "$dn" $ipsec_ca_save_file`
    if test -z "$delete_result" ; then
        test -z "$ca_dn" && echo "Give CA dn!" && exit 1
        delete_result=`grep "$dn" $ipsec_certs_save_file`
        test -z "$delete_result" && echo "No need to delete!" && exit 1
        delete_certs=1
    else
        delete_ca=1
    fi
    test -z "$delete_ca" && delete_ca=0
    test -z "$delete_certs" && delete_certs=1

    if test $delete_ca -eq 1 ; then
        delete_path=`echo $delete_result | awk -F':' '{ print $2 }'`
        delete_file=$ipsec_ca_save_file
    else
        delete_path=`echo $delete_result | awk -F':' '{ print $3 }'`
        delete_file=$ipsec_certs_save_file
    fi
    test -z "$delete_path" -o ! -e $delete_path && exit 1
    
    if test $delete_ca -eq 1 ; then
        sed -i "/$dn/"d $delete_file
    else
        sed -i "/$ca_dn:$dn/"d $delete_file
    fi
    rm -rf $delete_path
    echo "Delete \"$dn\" successfully!"
    exit 0
}

gen_ca() {
    ##
    # init variable
    ##
    test -z "$dn" && test -z "$ca_dn" && dn=$default_ca_dn
    test -z "$dn" && test -n "$ca_dn" && dn=$ca_dn
    test -z "$name" && test -z "$ca_name" && name=$default_ca_name
    test -z "$name" && test -n "$ca_name" && name=$ca_name

    ##
    # ca directory
    ##
    ca_dir=`echo $dn | sed "s/[,\ =]\{1,\}/_/g"`
    ca_path=${certs_gen_path}/ca/$ca_dir
    test -d $ca_path && echo "CA \"$dn\" already created!" && exit 1
    test ! -d ${certs_gen_path}/ca && mkdir ${certs_gen_path}/ca
    mkdir $ca_path
    
    ##
    # ca private key and Certificate name
    ##
    ca_private_key=$ca_path/${name}_private_key.pem
    ca_cert=$ca_path/${name}_cert.pem
    ipsec pki --gen --type $type --size 2048 --outform $outform > $ca_private_key
    ca_private_key_size=`ls -l $ca_private_key | awk -F' ' '{ print $5 }'`
    test $ca_private_key_size -lt 1 && rm -rf $ca_path && echo "Generate CA \"$dn\" private key failed!" && exit 1

    ##
    # generate ca Certificate
    ##
    ipsec pki --self --lifetime $lifetime --in $ca_private_key --dn "$dn" --ca --outform $outform > $ca_cert
    ca_cert_size=`ls -l $ca_cert | awk -F' ' '{ print $5 }'`
    test $ca_cert_size -lt 1 && rm -rf $ca_path &&  echo "Generate CA \"$dn\" failed!" && exit 1
    echo "Generate CA \"$dn\" successfully!"

    ##
    # write file 
    ##
    is_ca_already_exist_in_file=`test -e $ipsec_ca_save_file && grep "$dn" $ipsec_ca_save_file` 
    test -z "$is_ca_already_exist_in_file" && echo "$dn:$ca_path:`basename $ca_private_key`:`basename $ca_cert`" >> $ipsec_ca_save_file
    exit 0
}

gen_req() {
    name=`echo $dn | sed "s/.*CN=//g" | sed "s/,.*//g" | sed "s/\ /_/g"`
    req_private_key=${name}_private_key.pem
    req_pem=${name}_req.pem
    ipsec pki --gen --type $type --size 2048 --outform $outform > ./$req_private_key
    ipsec pki --req --in $req_private_key --type $type --dn "$dn" --outform $outform > ./$req_pem

    req_pem_size=`ls -l $req_pem | awk -F' ' '{ print $5 }'`
    test $req_pem_size -lt 1 && rm -f $req_private_key $req_pem &&  echo "Generate req \"$dn\" failed!" && exit 1
    echo "Generate req \"$dn\" successfully!"
    exit 0
}

certs_dealing() {
    if test -n "$certs_cert" -a -n "$certs_private_key"; then
        certs_already_exist=0
        if test -e $certs_cert -a -e $certs_private_key ; then
            dn=`ipsec pki --print --in $certs_cert | grep "subject" | sed "s/.*:\ *\"*\(.*\)\"$/\1/g"`
            certs_dir=`echo $dn | sed "s/[,\ =]\{1,\}/_/g"`
            certs_already_exist=2
        fi
    else
        certs_cert=""
        certs_private_key=""
        certs_dir=""
        certs_path=""
        
        test -z "$dn" && echo "Please input certificate dn!" && exit 1
        if test ! -e "$ipsec_certs_save_file" ; then
            certs_dir=`echo $dn | sed "s/[,\ =]\{1,\}/_/g"`
            certs_already_exist=0
        else
            certs_result=`grep "$dn" $ipsec_certs_save_file`
            if test -z "$certs_result" ; then
                certs_dir=`echo $dn | sed "s/[,\ =]\{1,\}/_/g"`
                certs_already_exist=0
            else
                certs_path=`echo $certs_result | awk -F':' '{ print $3 }'`
                certs_dir=`basename $certs_path`
                test -e $certs_path && certs_already_exist=1 || certs_already_exist=0
            fi
        fi
    fi
}

ca_dealing() {
    ##
    # find ca private ket and Certificate
    ##
    if test $package_certs -eq 1 -a -n "$ca_cert" ; then
        ca_dn=`ipsec pki --print --in $ca_cert | grep "subject" | sed "s/.*:\ *\"*\(.*\)\"$/\1/g"`
        ca_dir=`echo $ca_dn | sed "s/[,\ =]\{1,\}/_/g"`
        ca_path=$certs_gen_path/ca/$ca_dir
        if test ! -e $ca_path ; then
            mkdir -p $ca_path
            cp -f $ca_cert $ca_path
        fi

        ca_cert_tmp=`basename $ca_cert`
        ca_cert=$ca_path/$ca_cert_tmp
        ca_private_key=$ca_cert
        ca_already_exist=1
    elif test -n "$ca_private_key" -a -n "$ca_cert" ; then
        if test -e $ca_cert -a -e $ca_private_key ; then
            test ! -e $ca_cert && echo "ca cert [$ca_cert] does not exist!" && exit 1
            ca_dn=`ipsec pki --print --in $ca_cert | grep "subject" | sed "s/.*:\ *\"*\(.*\)\"$/\1/g"`
            ca_dir=`echo $ca_dn | sed "s/[,\ =]\{1,\}/_/g"`
            ca_path=$certs_gen_path/ca/$ca_dir
            if test ! -e $ca_path ; then
                mkdir -p $ca_path
                cp -f $ca_private_key $ca_path
                cp -f $ca_cert $ca_path
            fi

            ca_private_key_tmp=`test -n "$ca_private_key" && basename $ca_private_key`
            ca_cert_tmp=`basename $ca_cert`
            ca_private_key=$ca_path/$ca_private_key_tmp
            ca_cert=$ca_path/$ca_cert_tmp
            ca_already_exist=1
        fi
    else
        ca_cert=""
        ca_private_key=""
        ca_already_exist=0

        if test $certs_already_exist -eq 2 ; then
            certs_ca_dn=`ipsec pki --print --in $certs_cert | grep "issuer" | sed "s/.*:\ *\"*\(.*\)\"$/\1/g"`
            certs_ca_dir=`echo $certs_ca_dn | sed "s/[,\ =]\{1,\}/_/g"`
            certs_ca_path=$certs_gen_path/ca/$certs_ca_dir
            if test -e $certs_ca_path ; then
                ca_cert=`find $certs_ca_path -maxdepth 1 -type f | grep ".*cert.pem"`
                ca_private_key=`find $certs_ca_path  -maxdepth 1 -type f | grep ".*private_key.pem"`
                ca_path=`dirname $ca_cert`
                ca_dir=`basename $ca_path`
            else
                certs_ca_dn=""
            fi
        fi

        if test $certs_already_exist -eq 1; then
            ca_dn=`grep "$dn" $ipsec_certs_save_file | awk -F':' '{ print $1 }' | sed 1p -n`
            test -z "$ca_dn" && echo "Cannot get ca dn!" && exit 1
            ca_path=`grep "$ca_dn" $ipsec_ca_save_file | awk -F':' '{ print $2 }' | sed 1p -n`
            test -z "$ca_path" && echo "Cannot get ca path!" && exit 1
            test ! -e "$ca_path" && echo "Could not find ca path \"$ca_path\"!" && exit 1

            ca_private_key=`grep "$ca_dn" $ipsec_ca_save_file | awk -F':' '{ print $3 }' | sed 1p -n`
            test -z "$ca_private_key" && echo "Cannot get ca private key path!" && exit 1

            ca_cert=`grep "$ca_dn" $ipsec_ca_save_file | awk -F':' '{ print $4 }' | sed 1p -n`
            test -z "$ca_cert" && echo "Cannot get ca certificate path!" && exit 1

            ca_private_key=$ca_path/$ca_private_key
            ca_cert=$ca_path/$ca_cert
            ca_dir=`basename $ca_path`
            ca_already_exist=1
        fi

        if test $certs_already_exist -eq 0 ; then
            ca_dir=`echo $ca_dn | sed "s/[,\ =]\{1,\}/_/g"`
            ca_path=$certs_gen_path/ca/$ca_dir

            if test -e $ca_path ; then
                ca_cert=`find $ca_path -maxdepth 1 -type f | grep ".*cert.pem"`
                ca_private_key=`find $ca_path -maxdepth 1 -type f | grep ".*private_key.pem"`
                test -z "$ca_cert" && echo "Could not find ca certificate!" && exit 1
                test -z "$ca_private_key" && echo "Could not find ca private key!" && exit 1
                ca_path=`dirname $ca_cert`
                ca_dir=`basename $ca_path`
            else
                echo "Generate certificate \"$dn\" need CA \"$ca_dn\"!" && exit 1
            fi
        fi
    fi

    test $package_certs -eq 0 -a ! -e "$ca_private_key" && echo "CA private key \"$ca_private_key\" does not exist!" && exit 1
    test ! -e "$ca_cert" && echo "CA certificate \"$ca_cert\" does not exist!" && exit 1
}

gen_private() {
    private_key=$1
    ipsec pki --gen --type $type --size 2048 --outform $outform > ./${private_key}_private_key.pem
}

gen_public() {
    if test $# -lt 2; then
        private_key=""
        public_key=$1
    else
        private_key=$1
        public_key=$2
    fi
    if test -z "$private_key" -o ! -e "$private_key" ; then
        gen_private $public_key
        private_key=${public_key}_private_key.pem
    fi
    ipsec pki --pub --in $private_key --outform $outform > ${public_key}_public_key.pem
}

certs_gen_path=~/.ipsec_certs
package_path=$certs_gen_path/package
ipsec_ca_save_file=$certs_gen_path/.ipsec_ca_gen
ipsec_certs_save_file=$certs_gen_path/.ipsec_certs_gen
ipsec_sample_dn_file=$certs_gen_path/.ipsec_sample_dn
parser_args $@

test -z "$delete_flag" && delete_flag=0
if test $delete_flag -eq 1 ; then
    ca_certs_delete
    exit $?
fi

if test -n "$file" ; then
    get_para_from_conf
fi

default_outform=pem 
default_lifetime=730
default_ca_dn="C=CN, O=Sercomm, CN=cn@strongswan.org"
default_ca_name="sc"
default_certs_name="test"
default_certs_dn="C=CN, O=Sercomm, CN=$default_certs_name"
default_digest=sha512
default_type=rsa
default_package_name="ipsec"
test -z "$ca" && ca=0
test -z "$outform" && outform=$default_outform 
test -z "$lifetime" && lifetime=$default_lifetime
test -z "$gen_private_key" && gen_private_key=0
test -z "$gen_public_key" && gen_public_key=0
test -z "$gen_req" && gen_req=0
test -z "$type" && type=$default_type
test -z "$package_certs" && package_certs=0
test -z "$server_flag" && server_flag=0
test -z "$client_flag" && client_flag=1
test -z "$custom_flag" && custom_flag=0
test ! -d $certs_gen_path && mkdir -p $certs_gen_path 
test ! -e $ipsec_sample_dn_file && cp -f /home/anton/tools/ipsec/conf/.ipsec_sample_dn $ipsec_sample_dn_file

if test $gen_private_key -eq 1 ; then
    gen_private $private_key
    exit 0
fi

if test $gen_public_key -eq 1 ; then
    gen_public $private_key $public_key
    exit 0
fi

##
# gen ipsec certs request
##
if test $gen_req -eq 1 ; then
    gen_req
    exit $?
fi

##
# generate ca
## 
if test $ca -eq 1 ; then
    gen_ca
    exit $?
fi

##
# ca dealing
##
certs_dealing
ca_dealing 

##
# init variable
##
test -z "$dn" && test -z "$ca_dn" && dn=$default_certs_dn
test -z "$dn" && test -n "$ca_dn" && dn=$ca_dn
if test -n "$dn" -a -z "$name"; then
    #name=`echo "$dn" | sed "s/.*CN\ *=\ *\(.*\)$/\1/g"`
    name=`echo "$dn" | sed "s/.*CN\ *=\ *//g | sed "s/,.*//g"`
    test -z "$name" && echo "Certificate name cannot be null!" && exit 1
    name=${name//[\$\@\'\"+=,:|\\\!~?]*/}
    test -z "$name" && echo "Certificate name cannot be null!" && exit 1
    name=`echo $name | tr 'A-Z' 'a-z' | sed "s/\ /_/g"`
    test -z "$name" && echo "Certificate name cannot be null!" && exit 1
fi

##
# check whether package
##
test -z "$dn" -a -z "$certs_cert" -a -z "$certs_private_key" && echo "Input parameters error!" && exit 1
if test $certs_already_exist -ne 0 ; then
    certs_path=$certs_gen_path/ca/$ca_dir/$certs_dir

    if test $certs_already_exist -eq 2 ; then
        if test ! -e $certs_path ; then
            mkdir -p $certs_path
            cp $certs_cert $certs_private_key $certs_path
        fi

        ##
        # write file 
        ##
        is_certs_already_exist_in_file=`test -e $ipsec_certs_save_file && grep "$dn" $ipsec_certs_save_file` 
        test -z "$is_certs_already_exist_in_file" && echo "$ca_dn:$dn:$certs_path:${name}_private_key.pem:${name}_cert.pem" >> $ipsec_certs_save_file
    else
        certs_cert=$certs_path/${name}_cert.pem
        certs_private_key=$certs_path/${name}_private_key.pem
    fi
fi

if test $package_certs -eq 1 -a $certs_already_exist -gt 0 ; then
    certs_package
    exit 1
fi

##
# check whether already exist
##
test $certs_already_exist -gt 0 && echo "Certificate with subject \"$dn\" already created!" && exit 1
certs_path=$certs_gen_path/ca/$ca_dir/$certs_dir
test -d $certs_path && echo "Certificate with subject \"$dn\" already created!" && exit 1
mkdir -p $certs_path

##
# generate certificate private key
##
certs_private_key=$certs_path/${name}_private_key.pem
certs_public_key=$certs_path/${name}_public_key.pem
certs_cert=$certs_path/${name}_cert.pem
ipsec pki --gen --type $type --size 2048 --outform $outform > $certs_private_key
certs_private_key_size=`ls -l $certs_private_key | awk -F' ' '{ print $5 }'`
test $certs_private_key_size -lt 1 && rm -rf $certs_path && echo "Generate certificate \"$dn\" failed!" && exit 1

##
# generate certificate public key and certificate
##
ipsec pki --pub --in $certs_private_key --outform $outform > $certs_public_key
ipsec pki --issue --lifetime $lifetime --in $certs_public_key --digest sha512 \
          --cacert $ca_cert --cakey $ca_private_key \
          --dn "$dn" \
          --outform $outform > $certs_cert 
certs_cert_size=`ls -l $certs_cert | awk -F' ' '{ print $5 }'`
test $certs_cert_size -lt 1 && rm -rf $certs_path &&  echo "Generate certificate \"$dn\" failed!" && exit 1
echo "Generate certificate \"$dn\" successfully!" 

##
# write file 
##
is_certs_already_exist_in_file=`test -e $ipsec_certs_save_file && grep "$dn" $ipsec_certs_save_file` 
test -z "$is_certs_already_exist_in_file" && echo "$ca_dn:$dn:$certs_path:${name}_private_key.pem:${name}_cert.pem" >> $ipsec_certs_save_file

if test $package_certs -eq 1 ; then
    certs_package
    exit 1
fi
exit 0
