#! /bin/bash
# Name : clang_complete
# Func : create .clang_complete config file 
# Time : 2015-10-20 16:42:20

conf_name=.clang_complete
include_path+="-I /usr/include/ \n"
include_path+="-I ~/tools/include/"
echo -e $include_path > $conf_name
find -type d | sed 's/^/-I &/g' >> $conf_name
