#! /bin/bash
# Name : fmake
# Func : create make project
# Time : 2016-03-24 14:46:05

test $# -ne 2 && echo "Usage: fmake [exec|lib|share] name"
test ! -d $2 && mkdir $2
case $1 in
    "lib")
    test ! -f $2/Makefile && cp $MAKEFILE_PATH/classification/Makefile-lib $2/Makefile
    ;;
    "share")
    test ! -f $2/Makefile && cp $MAKEFILE_PATH/classification/Makefile-share $2/Makefile
    ;;
    "exec")
    test ! -f $2/Makefile && cp $MAKEFILE_PATH/classification/Makefile-exec $2/Makefile
    ;;
    "proc")
    test ! -f $2/Makefile && cp $MAKEFILE_PATH/Makefile-project $2/Makefile
    ;;
esac

echo "Create project $2 successfully!"
