#! /bin/bash
# Name : ftpinfo-tool
# Func : 
# Time : 2015-10-13 18:41:25

function usage_print()
{
    echo "Usage: ftpinfo-tool [command] [option]"
    echo "[command]: add change del"
    echo "      ftpinfo-tool add ip user passwd"
    echo "      ftpinfo-tool change old_ip new_ip"
    echo "      ftpinfo-tool del ip"
}

test $# -lt 1 && usage_print && exit 1

ftp_conf_path=$TOOLS_PATH/conf/vsftpd-conf/ftp-tools/.vsftpd-conf.info
case "$1" in
    "add") 
        echo "$1:$2 $3" >> $ftp_conf_path
        ;;
    "change")
        sed -i "/$2/s/$2/$3/g" $ftp_conf_path
        ;;
    "del")
        sed -i "/$2/"d $ftp_conf_path 
        ;;
    *)
        usage_print
        exit 1
        ;;
esac
