#! /bin/bash
# Name : get_ip_by_mac
# Func : get_ip_by_mac 
# Time : 2015-10-21 19:19:32

gate_way_ip=`socket -g | awk -F: '{ print $2 }' | sed 's/\(\(.*\.\)\{3\}\)\(.*\)/\1/g'`
echo $gate_way_ip
test "$gate_way_ip" = "" && exit 1
nmap -sP "${gate_way_ip}"0/24 > /dev/null && arp -an | grep 08:00:27:c2:96:ea | awk '{
print $2 }' | sed 's/[()]//g'
