#! /bin/bash
# Name : lighttpd
# Func : 
# Time : 2015-12-26 09:50:55

case "$1" in
    "start")
    /usr/local/lighttpd/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf
    ;;
    "stop")
    killall lighttpd
    ;;
    "restart")
    killall lighttpd
    /usr/local/lighttpd/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf
    ;;
    "state")
    pidof lighttpd
    ;;
esac
