#! /bin/bash
#脚本功能：
	#生成vim中ctags插件所需的所文件
#创建时间：
	#2014-11-06 12:41:33

path=$@
if test $# -lt 1
then
    path=.
fi

#生成书签文件
#ctags --fields=+lS -R 
ctags -I __THROW -I __attribute_pure__ -I __nonnull -I __attribute__ \
    --file-scope=yes --langmap=c:+.h --languages=c,c++ --links=yes \
    --c-kinds=+p --c++-kinds=+p --fields=+liaS --extra=+q $path
    #-R -a $path
    #-f ~/.vim/systags

exit 0
