#! /bin/bash
# Name : printlib
# Func : print  lib of Makefile 
# Time : 2015-07-19 14:45:09

if test ! -e "./Makefile" ; then 
    echo "Makefile does not exist!"
    exit 1
fi

grep "^OTH_LIB =.*$" Makefile
