#! /bin/bash
# Name : vgrep
# Func : 
# Time : 2015-08-11 17:45:59

src=$(find -iname "*.c" -o -iname "*.h")

if test -z "$src" ; then
    exit 1
fi

for arg in $@
do
    if test "${arg:0:1}" = "-" ; then
        para+=$arg" "
    else
        str+=$arg".*"
    fi
done

len=${#str}
let len-=2
str=${str:0:$len}

grep -n $para $str $src --color=auto
