#! /bin/bash
# Name : ftp-get
# Func : 
# Time : 2015-10-13 11:17:02

test $# -lt 3 && echo "Usage: ftp-get ftp_server_ip directroy file1 file2 ..." && exit 1

# check whether is exit directroy
ftp_server_ip=$1
ftp_server_path=$2
shift 2

# get ftp server user and passwd
ftp_info=`ftpinfo $ftp_server_ip`
test $? -eq 1 -o "$ftp_info" = "" && echo "ftp server info read failed!" && exit 1

# download
ftp -n<<!
open $ftp_server_ip
user $ftp_info
binary
cd $ftp_server_path
lcd ./
hash
prompt
mget $@
close
bye
!

echo -e "download \033[0;35m$@\033[0m success!"
exit 0
