#! /bin/bash
# Name : ./dns-install
# Func : install dns setting 
# Time : 2015-12-23 12:40:53

get_ip (){
    ifconfig | grep "inet\ " | grep -v "127.0.0.1" | sed "s/.*inet.*:\ *\(.*\)\ .*:.*:.*$/\1/g"    
}

set_var_cache_bind_db_anton_com () {
    sed "s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/`get_ip`/g" /var/cache/bind/db.anton.com
}

