#! /bin/bash
# Name : getopt
# Func : 
# Time : 2015-07-31 15:15:24

function c1() {
cmd="rhc app create -p redhat"
while getopts :a:t:sn opt; do
    case $opt in
        a) cmd=$cmd" -a $OPTARG" ;;
        t) cmd=$cmd" -t $OPTARG" ;;
        s) cmd=$cmd" -s" ;;
        n) cmd=$cmd" -n --no-dns" ;;
        \?) echo "Invalid param" ;;
    esac
done
echo $cmd
}

c1 $@
